application: lights-project
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: main.php

- url: /main.php
  script: main.php

# - url: /map.php
#   script: map.php

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /maps/(.+\.php)$
  script: /maps/\1
- url: /maps/(.+)\.html
  static_dir: /maps/\1

# - url: /todo.txt
#   static_files: todo.txt